Add listEmptyText to README.MD
sauzy34/react-native-multi-selectbox pull request #40
Opened 2021-04-10 03:38 UTC by glinda93

2021-04-18 19:24 UTC, sauzy34 commented
@glinda93 Please add the same to `lib/README.md`.

2021-04-18 19:31 UTC, sauzy34 requested changes
@glinda93  Please update the same at lib/README.md.

2021-04-19 00:32 UTC, glinda93 commented
> @glinda93 Please update the same at lib/README.md.

Updated. Please check it out.

2021-04-20 12:31 UTC, sauzy34 approved these changes

2021-04-20 12:31 UTC, merged